### PR TITLE
add margin 0

### PR DESCRIPTION
**Pull request by kudryavtsevda**
add lost controllers and views

save into db is working fine without any changes.

### CODE REVIEW

**Comment by hishamco** [comment]
> add lost controllers and views

The controller is not lost I just rename it to `AdminController` while it make sense

Please fetch the latest code, I don't know why your PR unable to merge, if you need help please ping me in Gitter


Thanks

**Comment by hishamco** [comment]
Please fetch the lastes then create a branch from origin `dev` branch this way we are sure your branch is not behind

**Comment by kudryavtsevda** [comment]
> Please fetch the lastes then create a branch from origin `dev` branch this way we are sure your branch is not behind

I am confused because I have tried it several times without any success

**Comment by hishamco** [comment]
Let me simplify the thing:

1- Fork this repo
2- Install any Git Client such as "Fork"
3- Clone the repo using the Git client
4- Add remote named `upstream` pointing to `https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules.git`, now you should have two remote `origin` and `remote`
5- Right click on the `dev` branch on the remote and create a new branch
6- Start your lovely code then commit and push

**Comment by hishamco** [comment]
Fixed in https://github.com/OrchardCoreContrib/OrchardCoreContrib.Modules/commit/fac2faab0caface562d183a99393b48512090e71

Thanks a lot

**Pull request closed without merging**
